[package]
name = "taipan"
version = "0.1.0"
description = "A native jupyter notebook frontend"
authors = ["Liam <liam@scalzulli.com>"]
license = "CC0-1.0"
homepage = "https://github.com/terror/taipan"
repository = "https://github.com/terror/taipan"
edition = "2024"

[lib]
name = "taipan_lib"
crate-type = ["lib", "cdylib", "staticlib"]

[lints.clippy]
all = { level = "deny", priority = -1 }
arbitrary-source-item-ordering = "deny"
pedantic = { level = "deny", priority = -1 }
struct_field_names = "allow"
too_many_lines = "allow"
wildcard_imports = "allow"

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
futures = "0.3"
hex = "0.4.3"
hmac = "0.13.0"
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.151"
sha1 = "0.11.0"
sha2 = "0.11.0"
tauri = { version = "2", features = [] }
tauri-plugin-dialog = "2.7.2"
tempfile = "3.27.0"
thiserror = "2.0.19"
tokio = { version = "1", features = ["macros", "rt", "sync", "time"] }
typeshare = { version = "1.0.5", default-features = false }
zeromq = "0.6.0"
