[package]
name = "taipan"
version = "0.1.0"
description = "Taipan desktop application"
authors = ["Taipan"]
edition = "2024"

[lib]
name = "taipan_lib"
crate-type = ["lib", "cdylib", "staticlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
