[package]
name = "taipan"
version = "0.1.0"
description = "Taipan desktop application"
authors = ["Taipan"]
edition = "2024"

[lib]
name = "taipan_lib"
crate-type = ["lib", "cdylib", "staticlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.151"
tauri = { version = "2", features = [] }
tauri-plugin-dialog = "2.7.2"
tempfile = "3.27.0"
thiserror = "2.0.19"
typeshare = { version = "1.0.5", default-features = false }
