/*
 Generated by typeshare 1.13.3
*/

export interface NotebookCell {
	cell_type: string;
	source: string | string[];
	metadata: Record<string, unknown>;
	id?: string;
}

export interface NotebookDocument {
	cells: NotebookCell[];
	metadata: Record<string, unknown>;
	nbformat: number;
	nbformat_minor: number;
}

