/*
 Generated by typeshare 1.13.3
*/

export interface NotebookCell {
  cell_type: string;
  id?: string;
  metadata: Record<string, unknown>;
  source: string | string[];
}

export interface Notebook {
  cells: NotebookCell[];
  metadata: Record<string, unknown>;
  nbformat: number;
  nbformat_minor: number;
}
