/*
 Generated by typeshare 1.13.3
*/

export type MimeBundle = Record<string, unknown>;

export type Attachments = Record<string, MimeBundle>;

export type ExecutionCount = number | null;

export type Metadata = Record<string, unknown>;

export type NotebookCell = CodeCell | MarkdownCell | RawCell | UnknownCell;

export type NotebookOutput =
  DisplayDataOutput | ErrorOutput | ExecuteResultOutput | StreamOutput;

export type Source = string | string[];

export interface CodeCell {
  cell_type: 'code';
  execution_count: ExecutionCount;
  id?: string;
  metadata: Metadata;
  outputs: NotebookOutput[];
  source: Source;
}

export interface DisplayDataOutput {
  data: MimeBundle;
  metadata: Metadata;
  output_type: 'display_data';
}

export interface ErrorOutput {
  ename: string;
  evalue: string;
  output_type: 'error';
  traceback: string[];
}

export interface ExecuteResultOutput {
  data: MimeBundle;
  execution_count: ExecutionCount;
  metadata: Metadata;
  output_type: 'execute_result';
}

export interface MarkdownCell {
  attachments?: Attachments;
  cell_type: 'markdown';
  id?: string;
  metadata: Metadata;
  source: Source;
}

export interface Notebook {
  cells: NotebookCell[];
  metadata: Metadata;
  nbformat: number;
  nbformat_minor: number;
}

export interface RawCell {
  attachments?: Attachments;
  cell_type: 'raw';
  id?: string;
  metadata: Metadata;
  source: Source;
}

export interface StreamOutput {
  name: string;
  output_type: 'stream';
  text: Source;
}

export interface UnknownCell {
  cell_type: string;
  id?: string;
  metadata: Metadata;
  source?: Source;
}
