/*
 Generated by typeshare 1.13.3
*/

export type Instruction =
  | { opcode: 'binaryAdd'; argument?: undefined }
  | { opcode: 'binaryBitAnd'; argument?: undefined }
  | { opcode: 'binaryBitOr'; argument?: undefined }
  | { opcode: 'binaryBitXor'; argument?: undefined }
  | { opcode: 'binaryDiv'; argument?: undefined }
  | { opcode: 'binaryFloorDiv'; argument?: undefined }
  | { opcode: 'binaryLShift'; argument?: undefined }
  | { opcode: 'binaryMod'; argument?: undefined }
  | { opcode: 'binaryMul'; argument?: undefined }
  | { opcode: 'binaryPow'; argument?: undefined }
  | { opcode: 'binaryRShift'; argument?: undefined }
  | { opcode: 'binarySub'; argument?: undefined }
  | { opcode: 'binarySubscript'; argument?: undefined }
  | { opcode: 'buildList'; argument: number }
  | { opcode: 'buildString'; argument: number }
  | { opcode: 'buildTuple'; argument: number }
  | { opcode: 'callFunction'; argument: number }
  | { opcode: 'compareEq'; argument?: undefined }
  | { opcode: 'compareGe'; argument?: undefined }
  | { opcode: 'compareGt'; argument?: undefined }
  | { opcode: 'compareIn'; argument?: undefined }
  | { opcode: 'compareLe'; argument?: undefined }
  | { opcode: 'compareLt'; argument?: undefined }
  | { opcode: 'compareNe'; argument?: undefined }
  | { opcode: 'compareNotIn'; argument?: undefined }
  | { opcode: 'dup'; argument?: undefined }
  | { opcode: 'forIter'; argument: number }
  | { opcode: 'getIter'; argument?: undefined }
  | { opcode: 'jump'; argument: number }
  | { opcode: 'loadConst'; argument: number }
  | { opcode: 'loadFast'; argument: number }
  | { opcode: 'loadFree'; argument: number }
  | { opcode: 'loadName'; argument: number }
  | { opcode: 'makeFunction'; argument: number }
  | { opcode: 'pop'; argument?: undefined }
  | { opcode: 'popJumpIfFalse'; argument: number }
  | { opcode: 'popJumpIfTrue'; argument: number }
  | { opcode: 'return'; argument?: undefined }
  | { opcode: 'storeFast'; argument: number }
  | { opcode: 'storeFree'; argument: number }
  | { opcode: 'storeName'; argument: number }
  | { opcode: 'storeSubscript'; argument?: undefined }
  | { opcode: 'unpackSequence'; argument: number }
  | { opcode: 'unaryInvert'; argument?: undefined }
  | { opcode: 'unaryNeg'; argument?: undefined }
  | { opcode: 'unaryNot'; argument?: undefined }
  | { opcode: 'unaryPos'; argument?: undefined };

export interface Code {
  freevars: string[];
  instructions: Instruction[];
  locals: string[];
  names: string[];
}
