use super::*;

#[derive(Clone, Copy, Debug, Eq, PartialEq, Serialize)]
#[serde(tag = "opcode", content = "argument", rename_all = "camelCase")]
#[typeshare]
pub enum Instruction {
  BinaryAdd,
  BinaryBitAnd,
  BinaryBitOr,
  BinaryBitXor,
  BinaryDiv,
  BinaryFloorDiv,
  BinaryLShift,
  BinaryMod,
  BinaryMul,
  BinaryPow,
  BinaryRShift,
  BinarySub,
  BinarySubscript,
  BuildDict(u16),
  BuildList(u16),
  BuildString(u16),
  BuildTuple(u16),
  CallFunction(u8),
  #[serde(rename_all = "camelCase")]
  CallFunctionKeywords {
    keyword_names: u16,
    positional_count: u8,
  },
  CompareEq,
  CompareGe,
  CompareGt,
  CompareIn,
  CompareLe,
  CompareLt,
  CompareNe,
  CompareNotIn,
  Dup,
  ForIter(u16),
  GetIter,
  Jump(u16),
  LoadConst(u16),
  LoadFast(u16),
  LoadFree(u16),
  LoadName(u16),
  #[serde(rename_all = "camelCase")]
  MakeFunction {
    default_count: u8,
    function: u16,
  },
  Pop,
  PopJumpIfFalse(u16),
  PopJumpIfTrue(u16),
  Return,
  StoreFast(u16),
  StoreFree(u16),
  StoreName(u16),
  StoreSubscript,
  UnaryInvert,
  UnaryNeg,
  UnaryNot,
  UnaryPos,
  UnpackSequence(u16),
}
