use super::*;

#[derive(Clone, Copy, Debug, Eq, PartialEq, Serialize)]
#[serde(tag = "opcode", content = "argument", rename_all = "camelCase")]
#[typeshare]
pub enum Instruction {
  BinaryAdd,
  BinaryBitAnd,
  BinaryBitOr,
  BinaryBitXor,
  BinaryDiv,
  BinaryFloorDiv,
  BinaryLShift,
  BinaryMod,
  BinaryMul,
  BinaryPow,
  BinaryRShift,
  BinarySub,
  BuildString(u16),
  CallFunction(u8),
  CompareEq,
  CompareGe,
  CompareGt,
  CompareLe,
  CompareLt,
  CompareNe,
  Dup,
  Jump(u16),
  LoadConst(u16),
  LoadFast(u16),
  LoadFree(u16),
  LoadName(u16),
  MakeFunction(u16),
  Pop,
  PopJumpIfFalse(u16),
  PopJumpIfTrue(u16),
  Return,
  StoreFast(u16),
  StoreFree(u16),
  StoreName(u16),
  UnaryInvert,
  UnaryNeg,
  UnaryNot,
  UnaryPos,
}
